import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";
import StoreProvider from "./StoreProvider";
import FcmTokenComp from "@/components/shared/firebaseForeground";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// ravi2020mishra@gamil.com -pass 123456

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <div className="h-screen overflow-hidden flex flex-col">
            <FcmTokenComp />
            <Navbar />

            {children}
          </div>
        </StoreProvider>
        <Toaster position="top-center" reverseOrder={false} />

      </body>
    </html>
  );
}
